# Dockerfile for launching dch tool
#
# Usage :
#   docker build -t nginx-precise-dch -f Dockerfile-dch .
#   wget -qO - https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz | tar zxvf -
#   docker run -it -v $PWD:/local nginx-precise-dch bash -c '\
#       dch -M -v nginx_1.12.0-1~precise --distribution "precise" "Updated upstream."'
#

FROM ubuntu:precise
MAINTAINER Cyril Aknine "caknine@clever-age.com"

ENV TZ=Europe/Paris

RUN apt-get update && apt-get --no-install-recommends --no-install-suggests -y install devscripts libdistro-info-perl
